import { useState, useEffect } from "react";
import { useAuth } from "@/hooks/use-auth";
import { useLocation, Link, useSearch } from "wouter";
import { useQuery } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import SiteNavbar from "@/components/site-navbar";
import SiteFooter from "@/components/site-footer";
import { useLivery } from "@/hooks/use-livery";
import { useSEO } from "@/hooks/use-seo";
import { Mail } from "lucide-react";

type Mode = "login" | "register" | "reset";

interface InviteInfo {
  invitedEmail: string;
  invitedName: string;
  targetLevel: number;
  invitedByName: string;
  message: string | null;
  competition?: {
    id: number;
    title: string;
    description: string | null;
    category: string;
    coverImage: string | null;
  } | null;
}

const LEVEL_LABELS: Record<number, string> = {
  1: "Viewer",
  2: "Artist / Competitor",
  3: "Host",
  4: "Admin",
};

function getAuthDestination(search: string): string {
  const params = new URLSearchParams(search);
  const returnTo = params.get("returnTo");
  if (returnTo?.startsWith("/") && !returnTo.startsWith("//") && !returnTo.includes("\\")) {
    return returnTo;
  }
  return params.get("section") === "tax" ? "/dashboard?section=tax" : "/dashboard";
}

export default function LoginPage() {
  const { login, register, resetPassword, isAuthenticated, error } = useAuth();
  const [currentLocation, setLocation] = useLocation();
  const search = useSearch();
  const { toast } = useToast();
  const { getMedia } = useLivery();

  const params = new URLSearchParams(search);
  const inviteToken = params.get("invite") || "";
  const isRegisterPath = currentLocation === "/register";
  const requestedLevel = Number(params.get("level"));
  const initialLevel = [1, 2, 3].includes(requestedLevel)
    ? requestedLevel
    : !isRegisterPath && requestedLevel === 4
      ? 3
      : 1;
  const hasVoteTarget = Boolean(params.get("competitionId") && params.get("contestantId"));
  const returnToHasReferral = (() => {
    const returnTo = params.get("returnTo");
    if (!returnTo) return false;
    try {
      const returnParams = new URL(returnTo, window.location.origin).searchParams;
      return Boolean(returnParams.get("ref") || returnParams.get("referralCode"));
    } catch {
      return false;
    }
  })();
  const forwardedCode = params.get("referralCode");
  const isLegacyAutoGeneratedVoteCode = Boolean(
    hasVoteTarget
    && !params.get("ref")
    && forwardedCode
    && !returnToHasReferral
    && /^[A-F0-9]{8}$/i.test(forwardedCode.trim()),
  );
  const urlReferralCode = params.get("ref")
    || (isLegacyAutoGeneratedVoteCode ? null : forwardedCode);

  const [mode, setMode] = useState<Mode>(inviteToken ? "login" : isRegisterPath ? "register" : "login");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [displayName, setDisplayName] = useState("");
  const [selectedLevel, setSelectedLevel] = useState<number>(initialLevel);
  const [competitionEntryFeesAcknowledged, setCompetitionEntryFeesAcknowledged] = useState(false);
  const [hostEventFeesAcknowledged, setHostEventFeesAcknowledged] = useState(false);
  const [referralCode, setReferralCode] = useState(() => {
    if (urlReferralCode) return urlReferralCode.trim().toUpperCase();
    try {
      const inboundCode = localStorage.getItem("hfc_inbound_ref")?.trim().toUpperCase();
      if (inboundCode) return inboundCode;
      if (hasVoteTarget) return "";
      return localStorage.getItem("hfc_ref")?.trim().toUpperCase() || "";
    } catch {
      return "";
    }
  });
  const [referralCodeTouched, setReferralCodeTouched] = useState(false);
  const [loading, setLoading] = useState(false);

  const { data: inviteInfo } = useQuery<InviteInfo>({
    queryKey: ["/api/invitations/token", inviteToken],
    enabled: !!inviteToken,
  });

  const competitionIdForReferral = params.get("competitionId");
  const contestantIdForReferral = params.get("contestantId");
  const { data: targetReferralData } = useQuery<{ code: string | null }>({
    queryKey: ["/api/competitions", competitionIdForReferral, "contestants", contestantIdForReferral, "referral-code"],
    queryFn: async () => {
      const response = await fetch(
        `/api/competitions/${encodeURIComponent(competitionIdForReferral!)}/contestants/${encodeURIComponent(contestantIdForReferral!)}/referral-code`,
      );
      if (!response.ok) throw new Error("Could not load the contestant referral code");
      return response.json();
    },
    enabled: !!competitionIdForReferral && !!contestantIdForReferral && !referralCode,
    staleTime: 60 * 60_000,
  });

  const accountLevel = inviteInfo?.targetLevel ?? selectedLevel;
  const accountTypeLocked = Boolean(inviteToken);
  useSEO({
    title: inviteInfo?.competition?.title
      ? `Log in to ${inviteInfo.competition.title}`
      : "Sign In",
    description: inviteInfo?.competition?.description
      || "Log in to your The Quest account to continue with your invitation.",
    canonical: `${window.location.origin}/thequest/login`,
    ogImage: inviteInfo?.competition?.coverImage || undefined,
  });

  useEffect(() => {
    if (inviteInfo) {
      setEmail(inviteInfo.invitedEmail);
      setDisplayName(inviteInfo.invitedName);
      setSelectedLevel(inviteInfo.targetLevel);
    }
  }, [inviteInfo]);

  useEffect(() => {
    const incomingCode = urlReferralCode;
    if (incomingCode) {
      try {
        localStorage.setItem("hfc_ref", incomingCode.trim().toUpperCase());
        localStorage.setItem("hfc_inbound_ref", incomingCode.trim().toUpperCase());
        localStorage.removeItem("hfc_auto_ref");
      } catch {}
    }
  }, [search, urlReferralCode]);

  useEffect(() => {
    const code = targetReferralData?.code?.trim().toUpperCase();
    if (code && !referralCodeTouched && !referralCode) {
      setReferralCode(code);
      try {
        localStorage.setItem("hfc_ref", code);
        localStorage.setItem("hfc_auto_ref", JSON.stringify({
          code,
          competitionId: competitionIdForReferral,
          contestantId: contestantIdForReferral,
        }));
      } catch {}
    }
  }, [targetReferralData?.code, referralCode, referralCodeTouched, competitionIdForReferral, contestantIdForReferral]);

  useEffect(() => {
    if (isAuthenticated && !loading) {
      setLocation(getAuthDestination(search));
    }
  }, [isAuthenticated, loading, search, setLocation]);

  if (isAuthenticated && !loading) {
    return null;
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    const destination = getAuthDestination(search);

    try {
      if (mode === "register") {
        if (inviteToken && !inviteInfo) {
          toast({ title: "Please wait for your invitation details to load", variant: "destructive" });
          setLoading(false);
          return;
        }
        if (!displayName.trim()) {
          toast({ title: accountLevel === 1 ? "Please enter your name" : "Please enter a display name", variant: "destructive" });
          setLoading(false);
          return;
        }
        if (accountLevel === 2 && !competitionEntryFeesAcknowledged) {
          toast({ title: "Please confirm you understand competition entry fees may apply", variant: "destructive" });
          setLoading(false);
          return;
        }
        if (accountLevel === 3 && !hostEventFeesAcknowledged) {
          toast({ title: "Please confirm you understand hosting fees may apply", variant: "destructive" });
          setLoading(false);
          return;
        }
      }

      if (mode === "login") {
        if (inviteToken && !inviteInfo) {
          toast({ title: "Please wait for your invitation details to load", variant: "destructive" });
          return;
        }

        await login(email, password, inviteToken || undefined, accountLevel);

        toast({ title: "Welcome back!", description: "You have been logged in." });
        setLocation(destination);
      } else if (mode === "register") {
        if (password !== confirmPassword) {
          toast({ title: "Passwords don't match", variant: "destructive" });
          setLoading(false);
          return;
        }
        if (password.length < 6) {
          toast({ title: "Password must be at least 6 characters", variant: "destructive" });
          setLoading(false);
          return;
        }
        const registerLevel = inviteToken ? undefined : accountLevel;
        const normalizedReferralCode = referralCode.trim().toUpperCase();
        try {
          if (normalizedReferralCode) {
            localStorage.setItem("hfc_ref", normalizedReferralCode);
            const targetCode = targetReferralData?.code?.trim().toUpperCase();
            if (normalizedReferralCode === targetCode) {
              localStorage.setItem("hfc_auto_ref", JSON.stringify({
                code: normalizedReferralCode,
                competitionId: competitionIdForReferral,
                contestantId: contestantIdForReferral,
              }));
              if (urlReferralCode === normalizedReferralCode) {
                localStorage.setItem("hfc_inbound_ref", normalizedReferralCode);
              } else {
                localStorage.removeItem("hfc_inbound_ref");
              }
            } else {
              localStorage.removeItem("hfc_auto_ref");
              localStorage.setItem("hfc_inbound_ref", normalizedReferralCode);
            }
          } else {
            localStorage.removeItem("hfc_ref");
            localStorage.removeItem("hfc_inbound_ref");
            localStorage.removeItem("hfc_auto_ref");
          }
        } catch {}
        await register(email, password, displayName.trim(), inviteToken || undefined, registerLevel, {
          competitionEntryFeesAcknowledged,
          hostEventFeesAcknowledged,
          referralCode: normalizedReferralCode || undefined,
        });
        toast({ title: "Account created!", description: "Welcome to the platform." });
        setLocation(destination);
      } else if (mode === "reset") {
        await resetPassword(email);
        toast({ title: "Reset email sent", description: "Check your inbox for a password reset link." });
        setMode("login");
      }
    } catch (err: any) {
      const isAlreadyExists = err.message?.toLowerCase().includes("already in use") || err.message?.toLowerCase().includes("already exists");
      if (mode === "register" && isAlreadyExists) {
        toast({
          title: "Account already exists",
          description: inviteToken
            ? "Your account was pre-created. Log in below — check your invitation email for your temporary password."
            : "An account with this email already exists. Please log in instead.",
          variant: "destructive",
        });
        setMode("login");
      } else {
        const msg = err.message?.replace(/^\d+:\s*/, "") || "Something went wrong";
        toast({ title: "Error", description: msg, variant: "destructive" });
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-black text-white">
      <SiteNavbar />

      <div className="relative h-[300px] flex items-end justify-center overflow-hidden">
        {(() => { const m = getMedia("breadcrumb_bg"); return m.type === "video" && m.url ? (
          <video src={m.url} className="absolute inset-0 w-full h-full object-cover" autoPlay muted loop playsInline />
        ) : m.url ? (
          <div className="absolute inset-0 bg-cover bg-center" style={{ backgroundImage: `url('${m.url}')` }} />
        ) : <div className="absolute inset-0 bg-zinc-950" />; })()}
        <div className="absolute inset-0 bg-black/60" />
        <div className="relative z-10 bg-white px-10 py-4 mb-[-1px]">
          <h1
            className="text-black text-2xl font-bold uppercase"
            style={{ letterSpacing: "10px", fontFamily: "'Playfair Display', serif" }}
            data-testid="text-page-title"
          >
            {mode === "login" ? "LOGIN" : mode === "register" ? "REGISTER" : "RESET PASSWORD"}
          </h1>
        </div>
      </div>

      <div className="max-w-md mx-auto px-4 py-16">
        {inviteInfo && mode === "login" && (
          <div className="rounded-md bg-gradient-to-r from-orange-500/10 to-amber-500/10 border border-orange-500/20 p-4 mb-6" data-testid="invite-banner">
            <div className="flex items-start gap-3">
              {inviteInfo.competition?.coverImage && (
                <img
                  src={inviteInfo.competition.coverImage}
                  alt=""
                  className="h-16 w-16 rounded object-cover shrink-0"
                />
              )}
              <div className="min-w-0">
                <div className="flex items-center gap-2 mb-2">
                  <Mail className="h-4 w-4 text-orange-400" />
                  <span className="text-sm font-medium text-orange-400">Your invitation</span>
                </div>
                {inviteInfo.competition?.title && (
                  <h2 className="text-base font-semibold text-white truncate">{inviteInfo.competition.title}</h2>
                )}
              </div>
            </div>
            <p className="text-sm text-white/60">
              <span className="text-white">{inviteInfo.invitedByName}</span> invited you to participate as a <Badge className={`border-0 text-xs ml-1 ${inviteInfo.targetLevel === 3 ? "bg-purple-500/20 text-purple-300" : inviteInfo.targetLevel === 2 ? "bg-blue-500/20 text-blue-400" : "bg-white/10 text-white/50"}`}>{LEVEL_LABELS[inviteInfo.targetLevel] || `Level ${inviteInfo.targetLevel}`}</Badge>
            </p>
            {inviteInfo.competition?.description && (
              <p className="text-xs text-white/45 mt-2 line-clamp-2">{inviteInfo.competition.description}</p>
            )}
            {inviteInfo.message && (
              <p className="text-xs text-white/40 mt-2 italic">"{inviteInfo.message}"</p>
            )}
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-6">
          {mode === "login" && !inviteToken && (
            <div
              className="rounded-md border border-orange-500/20 bg-orange-500/[0.06] px-4 py-3 text-sm text-white/70"
              data-testid="login-account-routing-note"
            >
              Select the account type that matches your sign-in. Choose Host/Admin for either a host or administrator account.
            </div>
          )}

          {(mode === "login" || mode === "register") && (
            <div>
              <Label htmlFor="select-account-type" className="text-white/60 uppercase text-xs tracking-wider">
                Account Type
              </Label>
              {accountTypeLocked ? (
                <Input
                  id="select-account-type"
                  value={LEVEL_LABELS[accountLevel] || "Invitation account"}
                  readOnly
                  aria-readonly="true"
                  className="mt-2 min-h-11 cursor-not-allowed border-white/20 bg-white/[0.08] text-white/80"
                  data-testid="select-account-type-locked"
                />
              ) : (
                <Select
                  value={String(accountLevel)}
                  onValueChange={(value) => {
                    setSelectedLevel(Number(value));
                    setCompetitionEntryFeesAcknowledged(false);
                    setHostEventFeesAcknowledged(false);
                  }}
                >
                  <SelectTrigger
                    id="select-account-type"
                    className="mt-2 min-h-11 bg-white/[0.08] text-white"
                    data-testid="select-account-type"
                  >
                    <SelectValue placeholder="Select account type" />
                  </SelectTrigger>
                  <SelectContent className="bg-[#1a1a1a] border-white/20">
                    <SelectItem value="1" className="text-white focus:bg-white/10 focus:text-white" data-testid="select-item-viewer">
                      Viewer
                    </SelectItem>
                    <SelectItem value="2" className="text-white focus:bg-white/10 focus:text-white" data-testid="select-item-talent">
                      Artist / Competitor
                    </SelectItem>
                    <SelectItem value="3" className="text-white focus:bg-white/10 focus:text-white" data-testid="select-item-host">
                      {mode === "login" ? "Host/Admin" : "Host"}
                    </SelectItem>
                  </SelectContent>
                </Select>
              )}
              <p className="mt-1.5 text-xs text-white/45">
                {mode === "login" && !inviteToken
                  ? accountLevel === 3
                    ? "Use this option for either Host or Admin accounts."
                    : "Choose the account type associated with your sign-in."
                  : inviteToken
                  ? "Your invitation sets this account type."
                  : accountLevel === 1
                    ? "Browse and vote on your favorite contestants."
                    : accountLevel === 2
                      ? "Create an artist profile and enter competitions."
                      : accountLevel === 3
                        ? "Create a Host account to submit event proposals."
                        : ""}
              </p>
            </div>
          )}

          {mode === "register" && (
            <div>
              <Label htmlFor="displayName" className="text-white/60 uppercase text-xs tracking-wider">
                {accountLevel === 1 ? "Name" : accountLevel === 3 ? "Host or Organization Name" : "Display Name"}
              </Label>
              <Input
                id="displayName"
                type="text"
                value={displayName}
                onChange={(e) => setDisplayName(e.target.value)}
                className="mt-2 bg-white/[0.08] text-white"
                placeholder={accountLevel === 1 ? "Your full name" : accountLevel === 3 ? "Your name or organization" : "Your artist or stage name"}
                autoComplete="name"
                required
                data-testid="input-display-name"
              />
            </div>
          )}

          <div>
            <Label htmlFor="email" className="text-white/60 uppercase text-xs tracking-wider">
              Email
            </Label>
            <Input
              id="email"
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className="bg-white/[0.08] border-white/20 text-white mt-2"
              placeholder="your@email.com"
              autoComplete="email"
              required
              data-testid="input-email"
            />
          </div>

          {mode === "register" && (
            <div>
              <Label htmlFor="referral-code" className="text-white/60 uppercase text-xs tracking-wider">
                Promo / Referral Key (Optional)
              </Label>
              <Input
                id="referral-code"
                type="text"
                value={referralCode}
                onChange={(event) => {
                  setReferralCodeTouched(true);
                  setReferralCode(event.target.value.toUpperCase());
                }}
                className="mt-2 bg-white/[0.08] text-white"
                placeholder="Enter a promo or referral key"
                autoComplete="off"
                maxLength={20}
                data-testid="input-registration-referral-code"
              />
              <p className="mt-1.5 text-xs text-white/45">
                Referral links and the contestant you’re voting for can fill this in automatically.
              </p>
            </div>
          )}

          {mode !== "reset" && (
            <div>
              <Label htmlFor="password" className="text-white/60 uppercase text-xs tracking-wider">
                Password
              </Label>
              <Input
                id="password"
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="bg-white/[0.08] border-white/20 text-white mt-2"
                placeholder="Min 6 characters"
                autoComplete={mode === "register" ? "new-password" : "current-password"}
                minLength={mode === "register" ? 6 : undefined}
                required
                data-testid="input-password"
              />
            </div>
          )}

          {mode === "register" && (
            <div>
              <Label htmlFor="confirmPassword" className="text-white/60 uppercase text-xs tracking-wider">
                Confirm Password
              </Label>
              <Input
                id="confirmPassword"
                type="password"
                value={confirmPassword}
                onChange={(e) => setConfirmPassword(e.target.value)}
                className="bg-white/[0.08] border-white/20 text-white mt-2"
                placeholder="Repeat password"
                autoComplete="new-password"
                required
                data-testid="input-confirm-password"
              />
            </div>
          )}

          {mode === "register" && accountLevel === 2 && (
            <div className="flex min-h-12 items-start gap-3 rounded-md border border-white/15 bg-white/[0.03] px-3 py-3">
              <Checkbox
                id="competition-entry-fees-acknowledged"
                checked={competitionEntryFeesAcknowledged}
                onCheckedChange={(checked) => setCompetitionEntryFeesAcknowledged(checked === true)}
                aria-required="true"
                className="mt-0.5 border-white/40 data-[state=checked]:border-[#FF5A09] data-[state=checked]:bg-[#FF5A09]"
                data-testid="checkbox-competition-entry-fees"
              />
              <Label
                htmlFor="competition-entry-fees-acknowledged"
                className="cursor-pointer text-sm font-normal leading-relaxed text-white/75"
              >
                I understand that being nominated or entering competitions may require a nomination or registration fee.
              </Label>
            </div>
          )}

          {mode === "register" && accountLevel === 3 && (
            <div className="flex min-h-12 items-start gap-3 rounded-md border border-white/15 bg-white/[0.03] px-3 py-3">
              <Checkbox
                id="host-event-fees-acknowledged"
                checked={hostEventFeesAcknowledged}
                onCheckedChange={(checked) => setHostEventFeesAcknowledged(checked === true)}
                aria-required="true"
                className="mt-0.5 border-white/40 data-[state=checked]:border-[#FF5A09] data-[state=checked]:bg-[#FF5A09]"
                data-testid="checkbox-host-event-fees"
              />
              <Label
                htmlFor="host-event-fees-acknowledged"
                className="cursor-pointer text-sm font-normal leading-relaxed text-white/75"
              >
                I understand that submitting an event to host may require a hosting fee.
              </Label>
            </div>
          )}

          {error && (
            <p className="text-red-400 text-sm" data-testid="text-auth-error">{error}</p>
          )}

          <Button
            type="submit"
            disabled={loading}
            className="w-full bg-[#FF5A09] hover:bg-[#FF5A09]/80 text-white uppercase tracking-wider font-bold"
            style={{ borderRadius: 0 }}
            data-testid="button-auth-submit"
          >
            {loading ? "Please wait..." : mode === "login" ? "SIGN IN" : mode === "register" ? "CREATE ACCOUNT" : "SEND RESET EMAIL"}
          </Button>
        </form>

        <div className="mt-8 text-center space-y-3">
          {mode === "login" && (
            <>
              <button
                onClick={() => {
                  setMode("register");
                  setCompetitionEntryFeesAcknowledged(false);
                  setHostEventFeesAcknowledged(false);
                  if (!inviteToken && !params.has("level")) setSelectedLevel(1);
                }}
                className="text-[#FF5A09] text-sm uppercase tracking-wider hover:text-[#FF5A09]/70 transition-colors"
                data-testid="button-switch-register"
              >
                Don't have an account? Register
              </button>
              <br />
              <button
                onClick={() => setMode("reset")}
                className="text-white/40 text-sm hover:text-white/60 transition-colors"
                data-testid="button-forgot-password"
              >
                Forgot your password?
              </button>

            </>
          )}
          {mode === "register" && (
            <button
              onClick={() => setMode("login")}
              className="text-[#FF5A09] text-sm uppercase tracking-wider hover:text-[#FF5A09]/70 transition-colors"
              data-testid="button-switch-login"
            >
              Already have an account? Login
            </button>
          )}
          {mode === "reset" && (
            <button
              onClick={() => setMode("login")}
              className="text-[#FF5A09] text-sm uppercase tracking-wider hover:text-[#FF5A09]/70 transition-colors"
              data-testid="button-back-to-login"
            >
              Back to Login
            </button>
          )}
          <div className="mt-6 border-t border-white/10 pt-5" data-testid="login-host-prompt">
            <p className="text-sm text-white/55">
              Organizing a competition? Review hosting options and any applicable fees before submitting an event.
            </p>
            <Link
              href="/host"
              className="mt-2 inline-flex min-h-10 items-center gap-1 text-sm font-semibold uppercase tracking-wider text-[#FF5A09] transition-colors hover:text-orange-300"
              data-testid="link-login-host"
            >
              Learn about hosting <span aria-hidden="true">→</span>
            </Link>
          </div>
        </div>
      </div>

      <SiteFooter />
    </div>
  );
}
