// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/competition-summary/CompetitionSummaryText.tsx": () => import("../components/mockups/competition-summary/CompetitionSummaryText.tsx"),
  "./components/mockups/competition-summary/Current.tsx": () => import("../components/mockups/competition-summary/Current.tsx"),
  "./components/mockups/competition-summary/ReadableSummary.tsx": () => import("../components/mockups/competition-summary/ReadableSummary.tsx")
};
