import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Link, useLocation } from "wouter";

interface VoteAuthDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  competitionId?: number | null;
  contestantId?: number | null;
}

export function isVoteAuthenticationError(error: unknown): boolean {
  const message = error instanceof Error ? error.message : String(error ?? "");
  return /^\s*401(?:\s|:)/.test(message)
    || /\b(?:unauthenticated|authentication required|login required)\b/i.test(message);
}

export function VoteAuthDialog({ open, onOpenChange, competitionId, contestantId }: VoteAuthDialogProps) {
  const [location] = useLocation();
  const returnTo = `${location}${window.location.search}`;
  const authParams = new URLSearchParams({ returnTo });
  if (competitionId) authParams.set("competitionId", String(competitionId));
  if (contestantId) authParams.set("contestantId", String(contestantId));

  const currentParams = new URLSearchParams(window.location.search);
  let existingReferralCode =
    currentParams.get("referralCode")
    || currentParams.get("ref");
  if (!existingReferralCode) {
    try {
      existingReferralCode = localStorage.getItem("hfc_inbound_ref");
      if (!existingReferralCode) {
        const storedCode = localStorage.getItem("hfc_ref");
        let isKnownAutoPrefill = false;
        try {
          const autoPrefill = JSON.parse(localStorage.getItem("hfc_auto_ref") || "null");
          isKnownAutoPrefill = autoPrefill?.code?.trim().toUpperCase()
            === storedCode?.trim().toUpperCase();
        } catch {}
        const isLegacyAutoGeneratedCode = Boolean(
          competitionId
          && contestantId
          && storedCode
          && /^[A-F0-9]{8}$/i.test(storedCode.trim()),
        );
        if (!isKnownAutoPrefill && !isLegacyAutoGeneratedCode) {
          existingReferralCode = storedCode;
        }
      }
    } catch {
      existingReferralCode = null;
    }
  }
  if (existingReferralCode) authParams.set("referralCode", existingReferralCode);

  const authQuery = authParams.toString();

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="w-[calc(100vw-2rem)] max-h-[90dvh] max-w-md overflow-y-auto border-white/10 bg-[#111] text-white">
        <DialogHeader>
          <DialogTitle className="text-lg font-semibold">
            Log in or create an account to vote
          </DialogTitle>
          <DialogDescription className="text-white/60">
            An account is required to cast a vote. You’ll return to this competition afterward.
          </DialogDescription>
        </DialogHeader>

        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
          <Button
            asChild
            className="min-h-11 w-full rounded-none bg-[#FF5A09] font-bold text-white hover:bg-[#E84F06]"
          >
            <Link href={`/login?${authQuery}`} onClick={() => onOpenChange(false)}>
              Log in
            </Link>
          </Button>
          <Button
            asChild
            variant="outline"
            className="min-h-11 w-full rounded-none border-white/25 bg-transparent font-bold text-white hover:bg-white/10"
          >
            <Link href={`/register?${authQuery}`} onClick={() => onOpenChange(false)}>
              Create account
            </Link>
          </Button>
        </div>

        <p className="text-center text-xs leading-relaxed text-white/45">
          After signing in, tap Vote again to submit your vote.
        </p>
      </DialogContent>
    </Dialog>
  );
}